**Intro**
	 An exception occurs when python detects an error in your code. there are lots of exceptions that can be raised. when python encounters an unhandled exception it raises an error and terminates the code. 
**15.1**
	Here is a list of errors and when they would be raised: 
	**SyntaxError**
	Before python executes code it reads over all of it this step is called parsing.  When python is parsing through the code if it catches a syntactical error it will raise a SyntaxError
	**IndentionError**
	These are subtypes of SyntaxErrors. They also occur during parsing of the code. If you have a brain you guess what is wrong with your code when these errors are raised.
	**AttributeError**
	These errors can be raised for a multitude of reasons. One example could be if you misspelled the name of a module you imported or if you misspelled a method, unlike a SyntaxError these are raised a run time.
	**NameError**
	A NameError occurs when python can't  find and identifier. For example if you supply a function with a variable that has not been previously defined.
	**IndexError**
	Occurs when you try to access a element of a list with an index that does not exist. This happens often because python is zero indexed.
	**TypeError**
	Occurs when a value of one type is expected but another is supplied. for example if you try to concatenate a integer and a string a TypeError will be raised.
	**ValueError**
	A value error occurs when the operand is correct but the value is not. For example if we try to take the the square root of a negative number. 
	**ZeroDivisionError**
	You cant divide by zero. This is true for mod division and floor division.
	**FileNotFoundError**
	Occurs when you try to open a file that does not exist, is in the wrong directory, or misspelled. 
	**Note: this is not a complete list**
**15.2**
	What can we do to mitigate these errors? We use Try and Except blocks. The code with in a try block will be tried first and if the error is raised than the code within the except block will be executed. In action this looks like:
	```
	while True:
				try:
						user_input = input('Enter an interger: ')
						n = int(user_input)
						if n > 0: 
								break 
				except ValueError:
						print(f"{user_input} is not an int)
						```
	Another example would be a for an index error
	```
	lst = ['apple', 'cat', 'boat', 'drama']
			s = input('Enter a index for searching: ')
	try 
			i = lst.index(s)
			print(f'the value at {s} in {lst} is {i})
	except ValueError
			print(f'{s} was not in {lst})
			```
	There are two schools of thought when handling exceptions. One of them is the 'look before you leap approach where we check to see of the users input works and if it doesn't we deal with it immediately an example of this is: 
	```
	if s in lst 
				print(f'the index of {s} in {lst} is {lst.index(s)})
	else: 
				print(f'{s} was not found in {lst})
				```
	The other approach is the 'look before you leap' approach and that is the one that uses try and except blocks. It is usually easier to read code written this way but it is often that we as programer can not be expected to predict all the egregious errors that users a capable of creating. 
	**Note**
	- keep try blocks as small as possible
	- catch and handle small blocks 
	- try not to catch index, name or type errors
	- use separate blocks for separate errors
**15.3**
	Flow control 
	Really, keep try blocks as small as possible
	Handle exceptions in the most direct was possible
	Don't call functions within except blocks it disrupts flow
**16.1**
	Dictionaries are a ubiquitous method for data storage and entry. They are muteble. unlike a list or tuple we access values in a dictionary with keys. If we pretend that a python dictionary is like a Mariam-Webster dictionary a key would be the word and the definition would be the element or value that we are searching for.
	constructing a dictionary looks like:
	`d = ['apple': red fruit]
	Accessing an element looks like:
	`d['apple']
	This returns 'red fruit'
	You can add values to the dictionary quite easily
	`d['pear'] = 'shaped funny'
	`d['pineapple'] = 'spikey'
	If you try to access an element who's key does not exist it results in a KeyError
	you can overwrite elements in a dictionaries because they are mutable
	Keys bust be hashable aka immutable 
**16.2** 
	You can iterate over a dictionary yields its keys
	```
	 for x in fruit 
				print(x)
				-
	>>> apple 
	>>> pear 
	>>> pineapple
	```
	you can apply viewing objects while iterating over a dictionary if you want to view something other than just the keys.
	1. dict.keys( )
	2. dict.values( )
	3. dict.items( )
	-
	Here is how you would implement theses methods.
	```
	fruit = {'apple': ['red', 'round', 'sweet'],
							'pear': ['shape', 'green', 'sweet'],
							'pineapple': ['spiky', 'spongebob', 'yello']}
							-
	for value in dict.values( ):
					print(value)
					```
	It is also possible to iterate over a dictionary with tuple unpacking where:
	```
	for key, value in fruit.items( ):
					print(f"'{key}', value: '{value}')```

